services:
  - type: web
    name: task-management-api
    env: docker
    region: singapore
    plan: free
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: task-management-db
          property: connectionString

databases:
  - name: task-management-db
    region: singapore
    plan: free
    databaseName: taskmanagementdb
    ipAllowList: [] 